import 'package:flutter/material.dart';

import 'Parque.dart';

class ListParques {
  List<Parque> parques = [
    Parque(
      "Parque A",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      468,
      564,
      TimeOfDay(hour: 8, minute: 00),
      TimeOfDay(hour: 22, minute: 00),
      "Rua do Parque A",
      1.30,
      'assets/ImagensParques/parqueA.jpg',
    ),
    Parque(
      'Parque B',
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      33,
      3330,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      'Morada do Parque B',
      2.0,
      'assets/ImagensParques/parqueB.jpg',
    ),
    Parque(
      "Parque C",
      DISPONIBILIDADE.LOTADO,
      TIPOPARQUE.ESTRUTURA,
      251,
      251,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 0, minute: 00),
      "Rua do Parque C",
      2.10,
      'assets/ImagensParques/parqueC.jpeg',
    ),
    Parque(
      "Parque D",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      862,
      TimeOfDay(hour: 7, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua do Parque D",
      1.10,
      'assets/ImagensParques/parqueD.jpeg',
    ),
    Parque(
      "Parque E",
      DISPONIBILIDADE.LOTADO,
      TIPOPARQUE.ESTRUTURA,
      125,
      125,
      TimeOfDay(hour: 7, minute: 30),
      TimeOfDay(hour: 23, minute: 30),
      "Rua do Parque E",
      1.50,
      'assets/ImagensParques/parqueE.jpeg',
    ),
    Parque(
      "Parque F",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.ESTRUTURA,
      57,
      256,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      "Rua do Parque F",
      1.80,
      'assets/ImagensParques/parqueF.jpeg',
    ),
    Parque(
      "Parque G",
      DISPONIBILIDADE.QUASE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      489,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 0, minute: 00),
      "Rua do Parque G",
      2.30,
      'assets/ImagensParques/parqueG.jpeg',
    ),
    Parque(
      "Parque H",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      653,
      TimeOfDay(hour: 7, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua do Parque H",
      1.40,
      'assets/ImagensParques/parqueH.jpeg',
    ),
    Parque(
      "Parque I",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      521,
      TimeOfDay(hour: 7, minute: 30),
      TimeOfDay(hour: 23, minute: 30),
      "Rua do Parque I",
      1.20,
      'assets/ImagensParques/parqueI.jpg',
    ),
    Parque(
      "Parque J",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      256,
      299,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      "Rua do Parque J",
      1.20,
      'assets/ImagensParques/parqueJ.jpeg',
    ),
    Parque(
      "Parque K",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      12,
      251,
      TimeOfDay(hour: 8, minute: 00),
      TimeOfDay(hour: 22, minute: 00),
      "Rua do Parque K",
      1.20,
      null,
    ),
    Parque(
      "Parque L",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.ESTRUTURA,
      25,
      200,
      TimeOfDay(hour: 10, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua do Parque L",
      1.70,
      null,
    ),
    Parque(
      "Parque M",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      578,
      TimeOfDay(hour: 9, minute: 00),
      TimeOfDay(hour: 21, minute: 30),
      "Rua do Parque M",
      1.30,
      null,
    ),
    Parque(
      "Parque N",
      DISPONIBILIDADE.QUASE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      468,
      489,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 22, minute: 30),
      "Rua do Parque N",
      1.20,
      null,
    ),
    Parque(
      "Parque O",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      612,
      TimeOfDay(hour: 6, minute: 30),
      TimeOfDay(hour: 00, minute: 00),
      "Rua do Parque O",
      1.30,
      null,
    ),
  ];

  ListParques();
}
