import 'package:flutter/material.dart';

import 'Parque.dart';

class ListParques {
  List<Parque> parques = [
    Parque(
      "Calçada do Combro",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      468,
      564,
      10,
      TimeOfDay(hour: 8, minute: 00),
      TimeOfDay(hour: 22, minute: 00),
      "Rua da Calçada do Combro",
      1.30,
      'assets/ImagensParques/parqueA.jpg',
    ),
    Parque(
      'Combatentes',
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      33,
      330,
      20,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      'Morada dos Combatentes',
      2.0,
      'assets/ImagensParques/parqueB.jpg',
    ),
    Parque(
      "Avenida de Pádua - Olivais",
      DISPONIBILIDADE.LOTADO,
      TIPOPARQUE.ESTRUTURA,
      251,
      251,
      40,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 0, minute: 00),
      "Rua Avenida de Pádua - Olivais",
      2.10,
      'assets/ImagensParques/parqueC.jpeg',
    ),
    Parque(
      "Vila Maria",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      862,
      30,
      TimeOfDay(hour: 7, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua do Vila Maria",
      1.10,
      'assets/ImagensParques/parqueD.jpeg',
    ),
    Parque(
      "Estrada da Luz",
      DISPONIBILIDADE.LOTADO,
      TIPOPARQUE.ESTRUTURA,
      125,
      125,
      100,
      TimeOfDay(hour: 7, minute: 30),
      TimeOfDay(hour: 23, minute: 30),
      "Rua da Estrada da Luz",
      1.50,
      'assets/ImagensParques/parqueE.jpeg',
    ),
    Parque(
      "LIDL Av. Inf. D. Henrique",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.ESTRUTURA,
      57,
      256,
      92,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      "Rua do LIDL Av. Inf. D. Henrique",
      1.80,
      'assets/ImagensParques/parqueF.jpeg',
    ),
    Parque(
      "Parque da Graça",
      DISPONIBILIDADE.QUASE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      489,
      200,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 0, minute: 00),
      "Rua do Parque da Graça",
      2.30,
      'assets/ImagensParques/parqueG.jpeg',
    ),
    Parque(
      "Mercado de Alvalade",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      653,
      315,
      TimeOfDay(hour: 7, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua do Mercado de Alvalade",
      1.40,
      'assets/ImagensParques/parqueH.jpeg',
    ),
    Parque(
      "Chão do Loureiro",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      521,
      456,
      TimeOfDay(hour: 7, minute: 30),
      TimeOfDay(hour: 23, minute: 30),
      "Rua do Chão do Loureiro",
      1.20,
      'assets/ImagensParques/parqueI.jpg',
    ),
    Parque(
      "Manuel Gouveia",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      256,
      299,
      589,
      TimeOfDay(hour: 9, minute: 0),
      TimeOfDay(hour: 21, minute: 0),
      "Rua Manuel Gouveia",
      1.20,
      'assets/ImagensParques/parqueJ.jpeg',
    ),
    Parque(
      "Rego",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      12,
      251,
      952,
      TimeOfDay(hour: 8, minute: 00),
      TimeOfDay(hour: 22, minute: 00),
      "Rua do Rego",
      1.20,
      null,
    ),
    Parque(
      "Avenida Lusíada",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.ESTRUTURA,
      25,
      200,
      1250,
      TimeOfDay(hour: 10, minute: 00),
      TimeOfDay(hour: 23, minute: 00),
      "Rua da Avenida Lusíada",
      1.70,
      null,
    ),
    Parque(
      "Universidade",
      DISPONIBILIDADE.PARCIALMENTE_LOTADO,
      TIPOPARQUE.SUPERFICIE,
      468,
      578,
      1420,
      TimeOfDay(hour: 9, minute: 00),
      TimeOfDay(hour: 21, minute: 30),
      "Rua da Universidade",
      1.30,
      null,
    ),
    Parque(
      "Colégio Militar",
      DISPONIBILIDADE.QUASE_LOTADO,
      TIPOPARQUE.ESTRUTURA,
      468,
      489,
      1000,
      TimeOfDay(hour: 8, minute: 30),
      TimeOfDay(hour: 22, minute: 30),
      "Rua do Colégio Militar",
      1.20,
      null,
    ),
    Parque(
      "Mayer",
      DISPONIBILIDADE.DISPONIVEL,
      TIPOPARQUE.SUPERFICIE,
      468,
      612,
      2500,
      TimeOfDay(hour: 6, minute: 30),
      TimeOfDay(hour: 00, minute: 00),
      "Rua do Mayer",
      1.30,
      null,
    ),
  ];

  ListParques();
}
